---
# this should work with or without proxy, it must be set on the docker_install.yml playbook to apply globally
- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  when: ansible_pkg_mgr == "apt"

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  when: ansible_pkg_mgr == "apt"

- name: set up the stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: ansible_pkg_mgr == "apt"

- name: Update the apt package index
  apt: update_cache=yes
  when: ansible_pkg_mgr == "apt"

- name: Install the latest version of Docker
  apt: name=docker-ce state=latest
  when: ansible_pkg_mgr == "apt"

# install vim
- name: Install vim to edit docker compose files
  apt: name=vim state=latest
  when: ansible_pkg_mgr == "apt"