---
# Creador: Jorge Hevia
# Proposito: servir de ejemplo para futuros estudiantes del curso de ansible en GFI informatica
# Lo que hace: prepara una maquina debian para el estudio de Ansible, incluyendo un editor y todos los paquetes necesarios para
#             ansible 2.1.1.1.

- hosts: virtual  # declaramos los hosts a los que vamos a aplicar las tareas
  become: true    # utilizamos become para tener permisos de administrador de forma global (para todas las tareas de este playbook)
  ignore_errors: yes
  tasks:          # lista de tareas a realizar por ansible
#    - name: Adquisicion del repositorio oficial (eliminar en caso de no funcionar)          # le damos un nombre descriptivo a la tarea que vamos a realizar
#      apt_repository: repo='ppa=ansible/ansible'                                            # mediante el modulo 'apt_repository' anadimos el repositorio oficial ( http://docs.ansible.com/ansible/apt_repository_module.html )

    - name: Adquisicion del repositorio para sublime text 3
      apt_repository: repo='ppa:webupd8team/sublime-text-3'

    - name: Actualizacion de la cache de repositorios   # una vez anadido el repositorio, hacemos un "apt-get update" para actualizar la lista de repositorios
      apt: update_cache=yes                             # mediante el modulo apt actualizamos el repositorio ( http://docs.ansible.com/ansible/apt_module.html )

    - name: Instalacion de requisitos                   # instalamos todos los programas que podrian ser necesarior o recomendados para ansible 2.1.1.0
      apt: name={{item}}  state=latest                  # le damos el nombre del paquete y su estado, en este caso queremos que si esta instalado se actualice y si no, que se instale
      with_items:                                       # utilizamos una lista con todos los paquetes necesarios
        - sshpass
        - python-crypto-dbg
        - python-crypto-doc
        - python-jinja2-doc
        - ipython
        - python-netaddr-docs
        - software-properties-common

    - name: Instalacion de ansible    # instalamos finalmente ansible
      apt: name=ansible state=latest

    - name: Instalacion de sublime
      apt: name=sublime-text-installer state=latest
