---
# author: jorge hevia
# function: this playbook will install apache and all it's dependencies in the selected machines
- hosts: virtual
  become: true
  ignore_errors: yes
  vars:
    - extracted_files_folder: httpd-2.4.25
    - installation_folder: httpdd2
    - file_name: httpd-2.4.25.tar.bz2
    - download_url: http://apache.rediris.es//httpd/httpd-2.4.25.tar.bz2
  tasks:
    - name: install the dependencies for apache whatever the OS package manager is (experimental)
      package:
        name:  "{{ item }}"
        state: latest
      with_items:
        - libtool
        - autoconf
        - make
        - libapr1-dev
        - libaprutil1-dev
    - name: Download the installation files in the selected folder
      get_url:
        url: "{{download_url}}"
        dest: "/tmp/"
        mode: 664

    - name: Create httpd2 folder
      file: name="/opt/{{ installation_folder }}" state=directory

    - name: Extract the downloaded files
      unarchive: 
        src: "/tmp/{{ file_name }}"
        dest: "/opt/"
        remote_src: true

    - name: Configure apache
      shell: "/opt/{{ extracted_files_folder }}/configure --prefix=/opt/{{ installation_folder }}"

    - name: compile the files
      shell: "/opt/{{ extracted_files_folder }}/make"

    - name: install apache
      shell: "/opt/{{ extracted_files_folder }}/make install"