---
# Creador: Jorge Hevia
# Proposito: servir de ejemplo para futuros estudiantes del curso de ansible en GFI informatica
# Lo que hace: instalamos sublimetext para poder editar mas facilmente los playbook, esta vez lo hacemos proporcionando nosotros el instalador
# NOTA: EL ELEMENTO EN FILES ES UN SEÑUELO PARA MOSTRAR LA ESTRUCTURA DEL ROL, NO ES UN INSTALADOR REAL
  - name: Copiar a la maquina destino el instalador
    copy: src=sublime-text-installer.deb dest=/tmp/ mode=775  # copiamos el instalador que se encuentra en /ansible-enviroment-debian/files a /tmp

  - name: Instalacion de sublime
    apt: name=sublime-text-installer state=latest 

  - name: Eliminacion del instalador
    file: src=/tmp/sublime-text-installer.deb state=absent    # mediante el modulo "file" y el estado "absent" eliminamos el instalador...se podria decir que...lo hemos ausentado xDDD(matadme plis)